### ISSUE TITLE
Unable to use revert-staged-changes

### ISSUE THREAD

**Issue by ipsi** [pivotal-cf/om#103]
Attempting to use `revert-staged-changes` on several of our environments results in the following error:

```
could not execute "revert-staged-changes": could not fetch form: could not find the form authenticity token
```

Given a command like:

```
om --target https://pcf.reel.gcp.london.cf-app.com --skip-ssl-validation --username admin --password <password> revert-staged-changes
```

This happens on GCP 1.12, 1.11, 1.10, and 1.9 Ops Managers.

**Comment by zachgersh** [comment]
Hey @ipsi are you actually using a release of `om` or building it yourself?

I believe this issue is fixed on master now

https://github.com/pivotal-cf/om/commit/81bb6448b88ee51b9d3ca02d2b1fb45c84d0a103

The next release will have it but if you go build right now (on master) you can at least try out the fix before it officially ships. Would be great to get your feedback.

**Comment by ipsi** [comment]
@zachgersh I'm not really sure - I believe we're on `master`, having run `go get -u github.com/pivotal-cf/om`, but `om --version` returns `unknown`.

Even after removing the binary from my GOPATH and re-running `go get`, it still gives us the same error.

**Comment by madamkiwi** [comment]
Hi Andrew, this is similar to https://github.com/pivotal-cf/om/issues/102 which is specific to ops manager 1.12 (which, as Zach pointed out, is fixed on master but not yet released), however since you mentioned that it happens on 1.9-1.12 ops manager it could be a different issue.  Can you please reconfirm the versions that you are seeing the issue?

**Comment by ipsi** [comment]
@madamkiwi I've tried it on each of a GCP 1.9, 1.10, 1.11, and 1.12 environment, and I'm still seeing the issue.

Each environment was clean, with the only installed products being GCP and ERT.

The problem seems to be that if there are no staged changes, it explodes, rather than exiting gracefully with "no changes to revert" or something similar. If I staged a product, then the command ran without issue.

**Comment by davewalter** [comment]
Hi @ipsi. At that point, it sounds like an Ops Manager issue. Have you looked at the /debug/rails_log on your Ops Manager to see if there is any more context on the response from the request sent by `om`?

**Comment by ipsi** [comment]
@davewalter I'm afraid I've rolled onto another project, and won't have time to dig into this for a while. All I can say is that I experienced this issue across several different ops managers - it _could_ be an issue with each of them, but that seems a bit unlikely.

**Comment by davewalter** [comment]
Hi @ipsi. In that case, is there someone on the team you were on who can continue to represent the issue you experienced and follow-up with us?

**Comment by acrmp** [comment]
Hi Andrew,

We pushed a change caec5ed2f8c3390ab9fc2433ec4038bb555bd5ef in master to the behaviour of `revert-staged-changes` so that it will no longer error when there are no staged changes.

I'm closing this issue but please feel free to re-open if this is still an issue.

Cheers,

Andrew.
